const productsArray = [
    {
        id: 1,
        name: 'Iphone 13pro',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 1000,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone1.jpg',
    },
    {
        id: 2,
        name: 'Iphone 11xs',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 500,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone2.jpg',
    },
    {
        id: 3,
        name: 'Iphone 12',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 1500,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone3.jpg',
    },
    {
        id: 4,
        name: 'Iphone 10',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 900,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone4.jpg',
    },
    {
        id: 5,
        name: 'Iphone 9',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 600,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone5.jpg',
    },
    {
        id: 6,
        name: 'Iphone 9',
        description: 'This is a Iphone 11xs',
        type: 'phone',
        capacity: 126,
        price: 700,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone6.jpg',
    },
    {
        id: 7,
        name: 'Samsung Galaxy S22',
        description: 'This is a Samsung Galaxy S22',
        type: 'phone',
        capacity: 126,
        price: 1000,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/no-image.jpg',
    },
    {
        id: 8,
        name: 'Samsung A73',
        description: 'This is a Samsung A73',
        type: 'phone',
        capacity: 126,
        price: 1000,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone1.jpg',
    },
    {
        id: 9,
        name: 'Samsung Note 20',
        description: 'This is a Samsung Note 20',
        type: 'phone',
        capacity: 126,
        price: 500,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone2.jpg',
    },
    {
        id: 10,
        name: 'Samsung S21',
        description: 'This is a Samsung S21',
        type: 'phone',
        capacity: 126,
        price: 1500,
        image: 'https://github.com/teresa1707/images/blob/lesson-12/public/images/phone3.jpg',
    },
]

export const getProductsObject = (array) =>
    array.reduce(
        (obj, product) => ({
            ...obj,
            [product.id]: product,
        }),
        {}
    )

export default productsArray

// {
//     "products" : [
//     {
//         "id": 1,
//         "name": "Iphone 13pro",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 1000,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone1.jpg",
//     },
//     {
//         "id": 2,
//         "name": "Iphone 11xs",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 500,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone2.jpg",
//     },
//     {
//         "id": 3,
//         "name": "Iphone 12",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 1500,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone3.jpg",
//     },
//     {
//         "id": 4,
//         "name": "Iphone 10",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 900,
//        " image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone4.jpg",
//     },
//     {
//         "id": 5,
//         "name": "Iphone 9",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 600,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone5.jpg",
//     },
//     {
//         "id": 6,
//         "name": "Iphone 9",
//         "description": "This is a Iphone 11xs",
//         "type": "phone",
//         "capacity": 126,
//         "price": 700,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone6.jpg",
//     },
//     {
//         "id": 7,
//         "name": "Samsung Galaxy S22",
//         "description": "This is a Samsung Galaxy S22",
//         "type": "phone",
//         "capacity": 126,
//         "price": 1000,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/no-image.jpg",
//     },
//     {
//         "id": 8,
//         "name": "Samsung A73",
//         "description": "This is a Samsung A73",
//         "type": "phone",
//         "capacity": 126,
//         "price": 1000,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone6.jpg",
//     },
//     {
//         "id": 9,
//         "name": "Samsung Note 20",
//         "description": "This is a Samsung Note 20",
//         "type": "phone",
//         "capacity": 126,
//         "price": 500,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone5.jpg",
//     },
//     {
//         "id": 10,
//         "name": "Samsung S21",
//         "description": "This is a Samsung S21",
//         "type": "phone",
//         "capacity": 126,
//         "price": 1500,
//         "image": "https://raw.githubusercontent.com/teresa1707/images/lesson-12/public/images/phone1.jpg",
//     }
// ]
// }
